## SERVER PORT ##
server.port: 7000

## CLOUD CONFIG ##
spring.profiles.include: native
spring.cloud.config.server.native.search-locations: classpath:/repository/{profile}
security.basic.enabled: false
management.security.enabled: false